mysite/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path("success/", views.PaymentSuccessView.as_view(), name="success"),
    path("failed/", views.PaymentFailedView.as_view(), name="failed"),
    path('api/checkout-session/<int:product_id>/', views.create_checkout_session, name='create_checkout_session'),

]

mysite/myapp/urls.py
from django.urls import path
from myapp.views import (
    index,
    add_item,
    update_item,
    delete_item,
    ProductListView,
    ProductDetailView,
    ProductDeleteView,
    contact,
    ProductViewSet
)
from api import views
from django.conf.urls import include
from rest_framework import routers

app_name = "myapp"

router = routers.DefaultRouter()
router.register(r'product', views.ProductViewSet)
router.register(r'profile', views.ProfileViewSet)
router.register(r'orders', views.OrderDetailViewSet)

urlpatterns = [
    path("", index, name='index'),
    path("", ProductListView.as_view(), name="index"),
    path("<int:pk>/", ProductDetailView.as_view(), name="detail"),
    path("additem/", add_item, name="add_item"),
    path("updateitem/<int:my_id>/", update_item, name="update_item"),
    path("deleteitem/<int:pk>/", ProductDeleteView.as_view(), name="delete_item"),
    path('contact/', contact, name="contact"),
    path('productsapi/', ProductViewSet.as_view({'get': 'list'}), name='ProductViewSet'),
    path('api/', include(router.urls)),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("myapp.urls", namespace="myapp")),
    path("users/", include("users.urls", namespace="users")),
    path('cart/', include('cart.urls', namespace='cart')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/users/urls.py
from django.urls import path
from .views import register, profile, seller_profile
from django.contrib.auth.views import LoginView, LogoutView

app_name = "users"

urlpatterns = [
    # http://127.0.0.1:8000/users/
    path("register/", register, name="register"),
    path("login/", LoginView.as_view(template_name='users/login.html'), name="login"),
    path("logout/", LogoutView.as_view(template_name='users/logout.html'), name="logout"),
    path("profile/", profile, name="profile"),
    path("sellerprofile/<int:id>/", seller_profile, name="sellerprofile"),
]

mysite/myapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Product(models.Model):
    seller = models.ForeignKey(User, on_delete=models.CASCADE, default='8')
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    description = models.CharField(max_length=200)
    image = models.ImageField(blank=True, upload_to='images')

    def __str__(self):
        return self.name

mysite/myapp/views.py
import json
import stripe

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponseNotFound, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import DetailView, ListView, TemplateView
from django.views.generic.edit import DeleteView
from cart.forms import CartAddProductForm
from rest_framework import viewsets
from .serializers import ProductSerializer

from .models import Product

def contact(request):
    return render(request, 'myapp/contact.html')

def index(request):
    page_obj = items = Product.objects.all()

    item_name = request.GET.get("search")
    if item_name != "" and item_name is not None:
        page_obj = items.filter(name__icontains=item_name)

    paginator = Paginator(page_obj, 3)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {"page_obj": page_obj}
    return render(request, "myapp/index.html", context)


class ProductListView(ListView):
    model = Product
    template_name = "myapp/index.html"
    context_object_name = "items"
    paginate_by = 6


# def indexItem(request, my_id):
#     item = Product.objects.get(id=my_id)
#     context = {"item": item}
#     return render(request, "myapp/detail.html", context=context)


class ProductDetailView(DetailView):
    model = Product
    template_name = "myapp/detail.html"
    context_object_name = "item"
    pk_url_kwarg = "pk"
    
    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        product = self.get_object()
        cart_product_form = CartAddProductForm()
        context["product"] = product
        context["cart_product_form"] = cart_product_form
        context["stripe_publishable_key"] = settings.STRIPE_PUBLISHABLE_KEY
        return context
    def is_admin(request):
        if request.user.groups.filter(name="администраторы").exists() == True:
            return render(request, True)
        else:
            return render(request, False)


@login_required
def add_item(request):
    if request.method == "POST":
        name = request.POST.get("name")
        price = request.POST.get("price")
        description = request.POST.get("description")
        image = request.FILES["upload"]
        seller = request.user
        item = Product(
            name=name, price=price, description=description, image=image, seller=seller
        )
        item.save()
    return render(request, "myapp/additem.html")


def update_item(request, my_id):
    item = Product.objects.get(id=my_id)
    if request.method == "POST":
        item.name = request.POST.get("name")
        item.price = request.POST.get("price")
        item.description = request.POST.get("description")
        item.image = request.FILES.get("upload", item.image)
        item.save()
        return redirect("/myapp/")
    context = {"item": item}
    return render(request, "myapp/updateitem.html", context)


def delete_item(request, my_id):
    item = Product.objects.get(id=my_id)
    if request.method == "POST":
        item.delete()
        return redirect("/myapp/")
    context = {"item": item}
    return render(request, "myapp/deleteitem.html", context)


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy("myapp:index")



class ProductViewSet(viewsets.ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer

mysite/myapp/templates/myapp/additem.html
{% extends "myapp/base.html" %}

{% block content %}
<div class="ml-[200px]">
    <h1 class="text-2xl m-10 font-bold text-green-600"> Add New Item Below</h1>
    <form class="w-1/3 bg-white shadow-md m-10 px-8 py-8 " method="post" enctype="multipart/form-data">
    {% csrf_token %}
        <div class="mb-4 ">
            <label class="block text-gray-700 text-md font-bold mb-2" for="name">Item Name</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text" placeholder="Name..." name="name" id="name">
            <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="price">Item Price</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text" placeholder="Price..." name="price" id="price">
            <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="description">Item Description</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text" placeholder="Description..." name="description" id="description">
            <input class="block mt-4" type="file" accept="image/*" name="upload" id="upload">
            <button class="block bg-green-600 text-white p-3 mt-4" type="submit" name="Add Item" value="Add Item">Add Item</button>
        </div>
    </form>
</div>

{% endblock content %}

mysite/myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'myapp/styles.css' %}">
    <title>Document</title>
</head>
<body>

    {% include "myapp/navbar.html" %}

    {% block content %}
            TEXT
    {% endblock content %}
</body>
</html>

mysite/myapp/templates/myapp/contact.html
{% extends "myapp/base.html" %}

{% block content %}
<style>
    body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        text-align: center;
    }
    header {
        background-color: #f2f2f2;
        padding: 20px;
    }
    h1 {
        color: #333;
    }
    .contact-info {
        margin: 20px;
        text-align: left;
    }
</style>
<body>
    <header>
        <h1>Контактная информация</h1>
    </header>
    <div class="contact-info">
        <p><strong>Наш адрес:</strong> ул. Примерная, д. 123, г. Примерный</p>
        <p><strong>Телефон:</strong> +7 (123) 456-78-90</p>
        <p><strong>Email:</strong> info@example.com</p>
    </div>
    <footer>
        <p>&copy; 2023 Интернет-магазин</p>
    </footer>
</body>
{% endblock content %}

mysite/myapp/templates/myapp/deleteitem.html
{% extends "myapp/base.html" %}

{% block content %}
  <h1 class="text-2xl m-10 font bold">Delete Product</h1>
  <form class="bg-white shadow-md m-10 w-3/5 rounded px-8 pt-6 pb-8 mb-4" method="post">
    {% csrf_token %}
    <div class="mb-4">
        <label class="block text-gray text-sm font mb-2">Are you sure you want to delete this item</label>
        <label class="block text-gray text-sm font mb-2">{{ item.name}}</label>
        <img class="w-40 h-40" src="{{ item.image.url}}" alt="" srcset="">
    </div>
    <input class="bg-red-500 text-white px-5 py-2" type="submit" value="Confirm">
    <a class="button bg-green-500 text-white px-5 py-3" href="{% url 'myapp:index' %}">Cancel</a>
  </form>
{% endblock content %}

mysite/myapp/templates/myapp/detail.html
{% extends "myapp/base.html" %}
{% load humanize %}

{% block content %}
    <div class="flex p-10 w-full h-200">
        <img class="w-1/3" src="{{ item.image.url }}" alt="itemPhoto">
        <div class="w-2/3 text-xl ml-10 mt-5">
            <p class="mt-5">{{ item.name }}</p>
            <p class="mt-5 text-green-500">$ {{ item.price | intcomma }}</p>
            <p class="mt-5 text-gray-600">{{ item.description }}</p>
            <p class="mt-5 text-gray-600"><a href="{% url 'users:sellerprofile' item.seller.id %}">@{{ item.seller }}</a></p>
            <p class="mt-5 text-gray-600">{{ item.seller.profile.contact_number }}</p>
            {% if is_admin == True %}
                <button class="bg-green-500 text-white mt-[50px]"><a href="{% url 'myapp:update_item' item.id %}">Update Item</a></button>
                <button class="bg-red-500 text-white mt-[50px]"><a href="{% url 'myapp:delete_item' item.id %}">Delete Item</a></button>
            {% endif %}
            <form action="{% url 'cart:cart_add' product.id %}" method="post"> 
                {{ cart_product_form }} 
                {% csrf_token %} 
                <button type="submit" style="background-color: rgb(34, 197, 94); color: white; padding: 5px 10px; border-radius: 5px; text-decoration: none; border: none; cursor: pointer;">Add to cart</button> 
            </form>
        </div>
    </div>
{% endblock content %}

mysite/myapp/templates/myapp/index.html
{% extends "myapp/base.html" %}

{% block content %}
	<main class="mt-10 mx-auto max-w-7xl px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28">
		<div class="sm:text-center lg:text-left">
			<h1 class="text-4xl font-extrabold text-gray-900 sm:text-5xl md:text-6xl">
				<span class="block xl:inline">Эсклюзивные товары</span>
				<span class="block xl:inline text-green-500">По Супер Ценам</span>
			</h1>
			<p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">Вы можете заказать товар из любой точки мира. Доставка включена</p>
		</div>

		<div class="mt-5 p-10 justify-center">
			<h2>Search</h2>
			<form action="" method="get">
				<input type="text" name="search" id="" style="border: 2px solid rgb(34, 197, 94); border-radius: 5px;">
			</form>
		</div>

		<div class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 xl:grid-col-3 lg:grid-col-3 gap-5">
			{% for item in page_obj %}
				<a href="{% url 'myapp:detail' item.id %}">
					<div class="rounded overflow-hidden shadow-lg">
						<img class="w-full h-[400px]" src="{{item.image.url}}" alt="">
						<div class="px-6 py-4">
							<p class="font-bold text-xl mb-2">{{item.name}}</p>
							<p class="font-bold text-xl text-green-500 mb-2">$ {{item.price}}</p>
							<p class="font-bold text-xl text-indogo-500 mb-2">by: {{item.seller}}</p>
							<p class="text-gray-700 text-base">{{ item.description}}</p>
						</div>
					</div>
				</a>
			{% endfor %}
		</div>
		
		<div class="flex justify-center">
			{% if page_obj.has_previous %}
				<a href="?page=1" style="background-color: rgb(34, 197, 94); color: white; padding: 1px 6px; margin: 0 5px; border-radius: 5px; text-decoration: none;">First</a>
				<a href="?page={{ page_obj.previous_page_number }}" style="background-color: rgb(34, 197, 94); color: white; padding: 1px 6px; margin: 0 5px; border-radius: 5px; text-decoration: none;">Previous</a>
			{% endif %}
			<span class="bg-gray-300 text-gray-800 py-2 px-4">{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>
			{% if page_obj.has_next %}
				<a href="?page={{ page_obj.next_page_number }}" style="background-color: rgb(34, 197, 94); color: white; padding: 1px 6px; margin: 0 5px; border-radius: 5px; text-decoration: none;">Next</a>
				<a href="?page={{ page_obj.paginator.num_pages }}" style="background-color: rgb(34, 197, 94); color: white; padding: 1px 6px; margin: 0 5px; border-radius: 5px; text-decoration: none;">Last</a>
			{% endif %}
		</div>

	</main>




    
{% endblock content %}

mysite/myapp/templates/myapp/navbar.html
{% load static %}
<nav class="bg-white shadow-lg">
    <div class="max-w-6xl mx-auto px-4">
        <div class="flex justify-between">
            <div class="flex space-x-7">
                <div>
                    <a href="{% url 'myapp:index' %}" class="flex items-center px-2 py-4">
                        <img class="h-8 w-8" src="{% static 'myapp/images/shop.png' %}" alt="logo" />
                        <span class="text-gray-500 font-semibold text-xl">Tkach Shop</span>
                    </a>
                </div>
                <div class="items-center flex space-x-1">
                    <a href="{% url 'myapp:index' %}" class="py-4 px-2 text-gray-500 font-semibold {% if request.resolver_match.view_name == 'myapp:index' %}border-b-4 border-green-500{% endif %}">Home</a>
                    <a href="{% url 'myapp:add_item' %}" class="py-4 px-2 text-gray-500 font-semibold {% if request.resolver_match.view_name == 'myapp:add_item' %}border-b-4 border-green-500{% endif %}">Add Item</a>
                    <a href="{% url 'myapp:contact' %}" class="py-4 px-2 text-gray-500 font-semibold {% if request.resolver_match.view_name == 'myapp:contact' %}border-b-4 border-green-500{% endif %}">Contacts</a>
                    <a href="{% url 'cart:cart_detail' %}" class="py-4 px-2 text-gray-500 font-semibold {% if request.resolver_match.view_name == 'cart:cart_detail' %}border-b-4 border-green-500{% endif %}">Cart</a>
                    {% if user.is_authenticated %}
                        <a href="{% url 'users:profile' %}" class="flex items-center">
                            <img class="h-8 w-8 rounded-full" src="{{ user.profile.image.url }}" alt="avatar" />
                        </a>
                        <a class="py-4 px-2 text-gray-500 font-semibold" href="{% url 'users:logout' %}">Logout</a>
                    {% else %}
                        <a class="py-4 px-2 text-gray-500 font-semibold" href="{% url 'users:login' %}">Login</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</nav>

mysite/myapp/templates/myapp/payment_failed.html
{% extends "myapp/base.html" %}

{% block content %}
    <p>Payment failed</p>
{% endblock content %}

mysite/myapp/templates/myapp/payment_success.html
{% extends "myapp/base.html" %}

{% block content %}
    <p>You have successfully paid</p>
{% endblock content %}

mysite/myapp/templates/myapp/product_confirm_delete.html
<form action="" method="post">
    {% csrf_token %}
    <p>Do you want to delete {{ object }}</p>
    <input type="submit" value="Delete">
</form>

mysite/myapp/templates/myapp/updateitem.html
{% extends "myapp/base.html" %}

{% block content %}
<div class="ml-[200px]">
    <h1 class="text-2xl m-10 font-bold text-green-600"> Update New Item </h1>
    <form class="w-1/3 bg-white shadow-md m-10 px-8 py-8 " method="post" enctype="multipart/form-data">
    {% csrf_token %}
        <div class="mb-4 ">
            <label class="block text-gray-700 text-md font-bold mb-2" for="name">Item Name</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" value="{{ item.name }}" type="text" placeholder="Name..." name="name" id="name">
            <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="price">Item Price</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700"  value="{{ item.price }}" type="text" placeholder="Price..." name="price" id="price">
            <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="description">Item Description</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700"  value="{{ item.description }}" type="text" placeholder="Description..." name="description" id="description">
            <img class="w-20 h-20" src="{{ item.image.url}}" alt="" srcset="">
            <input class="block mt-4" type="file" accept="image/*" name="upload" id="upload">
            <button class="block bg-green-600 text-white p-3 mt-4" type="submit" name="Add Item" value="Add Item">Update Item</button>
        </div>
    </form>
</div>

{% endblock content %}